Feature/autocomplete input
UTDNebula/athena pull request #25
Opened 2022-03-13 07:03 UTC by iamwood

## Overview

Resolves #13 
Resolves #15 

This creates the ExpandableSearchGrid component, which will be used to add multiple search terms to the dashboard. This also includes the child components SearchTermCard and SearchBar (now separate from SplashPageSearchBar). From here, the calls to the API can be placed into the SearchBar component (and SplashPage variant) with little trouble.

## What Changed

The SearchBar now implements the Autocomplete component from Material-UI.
The SearchBar component is now solely used in the ExpandableSearchGrid, and the input on the splash page is referred to as SplashPageSearchBar, since the styling is significantly different between the two.

## Other Notes

The Autocomplete component currently refers to a JSON file of the Top 100 Films (used to test functionality). This will need to be replaced with the API call, and most of the groundwork is in-place already to do so.

2022-03-13 19:38 UTC, WillieCubed commented
#### 📝 Changed routes:


| [**/**](https://athena-hc0xvb2he-acmutd.vercel.app/) |
|:-:|
|<a href="https://athena-hc0xvb2he-acmutd.vercel.app/"><img src="https://images.weserv.nl?url=https://sjc.microlink.io/QmfVxvvhZLgnUt-q9cz0P3S3e5HpmlCd4o74dBmaKMbeVQWMJ7OmPUay-E-nRRJELs1f0Jx5v3jxckEdQad0kg.png&w=600" alt="Screenshot of /" width="300"></a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/pf1RoN3rybkasVSwdN46nG1U6toWKq3fwD3D6cvJNQzg5-n8GHlBDi4BB2bQIHPOLsKxugQG1vDfumvjdQPIQQ.png">(view full size)</a> |







Commit d2983e1960aa5d04353b0fd1516c126af2d11a6f (https://athena-hc0xvb2he-acmutd.vercel.app).

2022-03-13 20:08 UTC, eboysen requested changes
Some general things that need to be added and cleaned up before I finish review. On first glance, everything looks to be in good shape, but I would very much appreciate all of your component files be fully commented with doc comments and in line comments. The autocomplete components have some complicated logic that need to be more easily traced and explained in comments. Additionally, there appears to be some spacing issues on the splash page that I assume were put there while you were testing the component, but need to be fixed before this can be merged.
![image](https://user-images.githubusercontent.com/50427509/158076441-0bbfc5e3-675a-429a-807f-228fa0491ff1.png)

2022-03-13 20:08 UTC, eboysen commented on components/common/searchTermCard.tsx
> +  color: string;
This prop could be a little bit more descriptive that it currently is. Maybe legendColor? Color on its own might evoke bg color or text color as those are the standard uses for that prop name.

2022-03-13 20:08 UTC, eboysen commented on components/common/expandableSearchGrid.tsx
> +    // console.log("The searchTerms have updated to ", searchTerms);
remove unnecessary code comments that are not descriptive

2022-03-13 20:08 UTC, eboysen commented on components/common/expandableSearchGrid.tsx
> +const colors = ['#b71c1c', '#0d47a1', '#1b5e20'];
Not a problem for you to manage, but eventually we will probably move these colors into a global style or module folder and you'll import this as a variable just for code maintainability

2022-03-16 05:46 UTC, eboysen approved these changes
Things look good for now, I would still like to see a little bit more commenting on the code in the future, not just the headers of the components, especially when there is any complex logic involved like here. Fortunately the code is fairly readable and you did a good job cleaning it up, so I'm going to approve with the intent that this is further documented after launch. Nice Work!

2022-03-16 05:46 UTC, merged