Feat/styleguidist docs for graph components
UTDNebula/athena pull request #38
Opened 2022-04-23 16:31 UTC by penczak

## Overview

Describe your changes here at a high level, describing how this PR fits into the
rest of the project.

This PR adds interactive Styleguidist docs for all of our graph components. These will be useful to developers for quickly learning how these components work and what form their props should be in. 
This PR also does some refactors on the BoxGraph and RadialBarChart components. Previously, these two components required their props.series to be of unique formats, but now they accept the same { name: "", data: [] } format as all the other components. 

## What Changed

Screenshot of BoxGraph example. 
![image](https://user-images.githubusercontent.com/97853271/164914731-ff39c42a-0363-40a8-ab28-be2246a70049.png)
![image](https://user-images.githubusercontent.com/97853271/164914739-224c7e98-4a6f-4db6-a6c8-d7eeb6ee4b27.png)

And a couple of screenshots of GraphChoice. 
![image](https://user-images.githubusercontent.com/97853271/164914750-3bf948aa-62eb-4da4-a7c9-0f8de4c14c57.png)
![image](https://user-images.githubusercontent.com/97853271/164914778-621e4502-0a61-427c-ab48-7db53ee67e15.png)

2022-04-29 04:26 UTC, eboysen requested changes
Everything looks pretty solid so far. Some of the features didn't work quite as expected. For example I would have liked to see the adding of Axis lablels to also expand the datasets to match the new number of labels
![image](https://user-images.githubusercontent.com/50427509/165884958-33059c1f-6263-43d2-a185-9d6d5e0f971d.png)
Also doesn't appear to be working on the Line Graph or Radar Chart at all
![image](https://user-images.githubusercontent.com/50427509/165885110-e1b1560a-4467-41b7-907c-630f0c43d836.png)
![image](https://user-images.githubusercontent.com/50427509/165885171-97428557-f4ab-4ad4-a701-3fc3bec20acb.png)


One of the small issues that I noticed is not necessarily within the scope of this PR however. The Box Graph seems to have the ability to overflow when it goes from 1 series up to 2. 
![image](https://user-images.githubusercontent.com/50427509/165884878-a678c429-204c-4baa-9094-5f7064f113cf.png)

Other than that, it looks like great work. Let me know if you need anything!

2022-04-29 04:26 UTC, eboysen commented on components/graph/BoxGraph/BoxGraph.tsx
> +  const formattedSeries = props.series.map((value) => { return { x: value.name, y: value.data} })
Good use of map here to keep consistent formatting of data

2022-05-02 22:44 UTC, penczak commented
> For example I would have liked to see the adding of Axis lablels to also expand the datasets to match the new number of labels

I left it this way to show that you need to actually add more data when you add more xaxisLabels. I intentionally kept those separate. If you still think its a better design choice to have more data generated when you add labels, I could add that. 
> Also doesn't appear to be working on the Line Graph or Radar Chart at all

This is also because those graph types don't actually display any xaxisLabels beyond the number that matches the data it is given. I left the styleguidist like this to show those aspects of the graphs.

2022-05-03 05:08 UTC, eboysen approved these changes

2022-05-03 05:08 UTC, eboysen commented
That sounds like a good justification to me. Nice work on this, it looks great

2022-05-03 05:08 UTC, merged